// List of major UK cities
export const ukCities = [
  "London",
  "Birmingham",
  "Manchester",
  "Glasgow",
  "Liverpool",
  "Bristol",
  "Edinburgh",
  "Leeds",
  "Sheffield",
  "Cardiff",
  "Belfast",
  "Nottingham",
  "Newcastle upon Tyne",
  "Leicester",
  "Brighton",
  "Coventry",
  "Aberdeen",
  "Southampton",
  "Plymouth",
  "Reading",
  "Derby",
  "Swansea",
  "Milton Keynes",
  "Stoke-on-Trent",
  "Oxford",
  "Cambridge",
  "York",
  "Exeter",
  "Bath",
  "Dundee",
  "Norwich",
  "Preston",
  "Sunderland",
  "Bradford",
  "Wolverhampton",
  "Portsmouth",
  "Bournemouth",
  "Huddersfield",
  "Middlesbrough",
  "Blackpool"
];